name: M3U generator

on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    
    - name: Run main script
      run: |
        pwd
        chmod +x autorun.sh
        ./autorun.sh
    
    - name: Stage changes
      run: |
        git add -A
        ls -la
    
    - name: Commit and push
      run: |
        git commit -m "links are updated" || echo "No changes to commit"
        git push || echo "No changes to push"
